import { PermissionsBitField } from 'discord.js';

export const developersIds =
    process.env.ADMITED_DEVELOPERS?.split(',').map((id) => id.trim()) || [];

export const Permissions = PermissionsBitField.Flags;

export const permissionNames = {
    [`${Permissions.Administrator}`]: 'Administrador',
    [`${Permissions.AddReactions}`]: 'Agregar reacciones',
    [`${Permissions.AttachFiles}`]: 'Adjuntar archivos',
    [`${Permissions.BanMembers}`]: 'Banear miembros',
    [`${Permissions.ChangeNickname}`]: 'Cambiar Apodo',
    [`${Permissions.Connect}`]: 'Conectarse al canal de voz',
    [`${Permissions.CreateEvents}`]: 'Crear eventos',
    [`${Permissions.CreateGuildExpressions}`]: 'Crear expresiones',
    [`${Permissions.CreateInstantInvite}`]: 'Crear invitaciones',
    [`${Permissions.CreatePrivateThreads}`]: 'Crear hilos privados',
    [`${Permissions.CreatePublicThreads}`]: 'Crear hilos públicos',
    [`${Permissions.DeafenMembers}`]: 'Ensordecer miembros',
    [`${Permissions.EmbedLinks}`]: 'Enviar enlaces',
    [`${Permissions.KickMembers}`]: 'Expulsar miembros',
    [`${Permissions.ManageChannels}`]: 'Gestionar canales',
    [`${Permissions.ManageEvents}`]: 'Gestionar eventos',
    [`${Permissions.ManageGuild}`]: 'Gestionar servidor',
    [`${Permissions.ManageGuildExpressions}`]: 'Gestionar expresiones',
    [`${Permissions.ManageMessages}`]: 'Gestionar mensajes',
    [`${Permissions.ManageNicknames}`]: 'Gestionar apodos',
    [`${Permissions.ManageRoles}`]: 'Gestionar roles',
    [`${Permissions.ManageThreads}`]: 'Gestionar hilos',
    [`${Permissions.ManageWebhooks}`]: 'Gestionar webhooks',
    [`${Permissions.MentionEveryone}`]: 'Mencionar @everyone',
    [`${Permissions.ModerateMembers}`]: 'Gestionar miembros',
    [`${Permissions.MoveMembers}`]: 'Mover usuarios',
    [`${Permissions.MuteMembers}`]: 'Silenciar usuarios',
    [`${Permissions.PrioritySpeaker}`]: 'Prioridad de palabra',
    [`${Permissions.ReadMessageHistory}`]: 'Leer el historial de mensajes',
    [`${Permissions.RequestToSpeak}`]: 'Solicitar hablar',
    [`${Permissions.SendMessages}`]: 'Enviar mensajes',
    [`${Permissions.SendMessagesInThreads}`]: 'Enviar mensajes en los hilos',
    [`${Permissions.SendPolls}`]: 'Crear encuestas',
    [`${Permissions.SendTTSMessages}`]: 'Enviar texto a voz',
    [`${Permissions.SendVoiceMessages}`]: 'Enviar mensajes de voz',
    [`${Permissions.Speak}`]: 'Hablar',
    [`${Permissions.Stream}`]: 'Transmitir',
    [`${Permissions.UseApplicationCommands}`]: 'Usar comandos de aplicaciones',
    [`${Permissions.UseEmbeddedActivities}`]: 'Añadir reacciones',
    [`${Permissions.UseExternalApps}`]: 'Usar aplicaciones externas',
    [`${Permissions.UseExternalEmojis}`]: 'Usar emojis externos',
    [`${Permissions.UseExternalSounds}`]: 'Usar sonidos externos',
    [`${Permissions.UseExternalStickers}`]: 'User stickers externos',
    [`${Permissions.UseSoundboard}`]: 'Usar panel de sonidos',
    [`${Permissions.ViewAuditLog}`]: 'Ver auditoria de logs',
    [`${Permissions.ViewChannel}`]: 'Ver canales',
    [`${Permissions.ViewGuildInsights}`]: 'Ver insignias del servidor',
};
